plugins:
  lti_consumer_enabled:
    default: true
  lti_consumer_key:
    default: 'foo'
    client: false
  lti_consumer_secret:
    default: 'bar'
    client: false
  lti_consumer_authenticate_url:
    default: 'https://edx.org/foo'
    client: true

login:
  invite_only: true
  login_required: true
  must_approve_users: false
  enable_local_logins: true
  allow_new_registrations: true

users:
  email_editable: false
  username_change_period: 0